Automatic version bumping
elimu-ai/vitabu pull request #96
Opened 2022-05-20 19:43 UTC by hhio618

### Description
closes #94

2022-05-21 07:48 UTC, nya-elimuai commented on build.gradle
> +        classpath 'org.ajoberstar:gradle-git:+'
@hhio618 Would it be better if we put a specific version of the library?

2022-05-21 11:12 UTC, nya-elimuai requested changes
@hhio618 Thank you, this is really cool to see!

I tried running `./gradlew releasePrepare`, and got "unspecified" as the new versionName:

```
Bumping versionName from 1.1.4 to unspecified
Bumping versionCode from 1001004 to 1001005
```

<img width="356" alt="Screen Shot 2022-05-21 at 7 02 41 PM" src="https://user-images.githubusercontent.com/15718174/169648984-4fea09e7-fe7d-4a77-af22-d69e097f9177.png">

Would it be possible to set the `versionName` as well?

2022-05-21 14:29 UTC, hhio618 commented
Thanks, @nya-elimuai. you need to specify either `bumpType` or `bumpVersion` parameters to get this to work:
Example:
```
./gradlew releasePrepare -PbumpType=patch # will increase the patch number, choices=major,minor,patch
```
```
./gradlew releasePrepare -PbumpVersion=x.y.z # bump to a specific version.
```
I added an exception to prompt for either of these parameters.

2022-05-27 11:52 UTC, nya-elimuai commented on app/build.gradle
> +        if (project.properties.containsKey("bumpVersion")){
Add missing whitespace: `) {`

2022-05-27 12:11 UTC, nya-elimuai commented
> https://github.com/elimu-ai/vitabu/pull/96#issuecomment-1133643779

@hhio618 This is really cool! Tested with `./gradlew releasePrepare -PbumpType=patch`:

<img width="344" alt="Screen Shot 2022-05-27 at 8 08 06 PM" src="https://user-images.githubusercontent.com/15718174/170696668-77e18d2f-f905-4d9d-9bb0-58bbe00a5ab1.png">

<img width="346" alt="Screen Shot 2022-05-27 at 8 08 14 PM" src="https://user-images.githubusercontent.com/15718174/170696696-a1d3ceca-ec18-438c-89f0-d173b012a6ca.png">

2022-05-27 12:21 UTC, nya-elimuai requested changes
@hhio618 This is really great! Amazing work 👏🏽

I only have one final adjustment, when running `./gradlew releasePrepare -PbumpType=patch`: Instead of bumping the version _before_ the release, bump it _after_ the release. That way it would work the same as with the webapp release versioning.

Example: If the version looks like this before the release:
```gradle
versionCode 1001005
versionName '1.1.5-SNAPSHOT'
```
change it to 
```gradle
versionCode 1001005
versionName '1.1.5'
```

Then release (commit to Git).


And then (after the release), bump the version for the next iteration:
```gradle
versionCode 1001006
versionName '1.1.6-SNAPSHOT'
```

2022-05-27 17:56 UTC, hhio618 commented
@nya-elimuai Thanks for the review! I made the changes you mentioned.

2022-06-03 04:30 UTC, nya-elimuai commented on app/build.gradle
> +        def Clean = true
Make `Clean` lower-case: `clean`

2022-06-03 04:32 UTC, nya-elimuai commented on app/build.gradle
> +            if (headCommitMessage.indexOf("vitabu-") > -1) {
To make the solution scalable to other Android apps (with different names, can you change "vitabu-" into a variable? For example by using the `applicationId` variable instead?

2022-06-03 04:32 UTC, nya-elimuai commented on app/build.gradle
> +                def tagName = headCommitMessage.split("vitabu-")[1]
Same comment here as above.

2022-06-03 04:32 UTC, nya-elimuai commented on app/build.gradle
> +        if (Clean){
Change to `if (clean) {`

2022-06-03 04:38 UTC, nya-elimuai requested changes
Looks great! Only added a suggestion to use the `applicationId` variable.

2022-06-04 07:56 UTC, nya-elimuai approved these changes
Looks good. Thank you!

2022-09-19 07:26 UTC, merged